<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-E57FEQI" failures="1" tests="7" name="TestNG.TestNG_Assertions" time="0.168" errors="0" timestamp="2022-11-26T06:40:10 IST" skipped="0">
  <testcase classname="TestNG.TestNG_Assertions" name="test2" time="0.030"/>
  <system-out>
    <![CDATA[running test2 method]]>
  </system-out>
  <testcase classname="TestNG.TestNG_Assertions" name="test4" time="0.011"/>
  <system-out>
    <![CDATA[running test4 method]]>
  </system-out>
  <testcase classname="TestNG.TestNG_Assertions" name="test7" time="0.009">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at TestNG.TestNG_Assertions.test7(TestNG_Assertions.java:74)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test7 -->
  <system-out>
    <![CDATA[running test7 method]]>
  </system-out>
  <testcase classname="TestNG.TestNG_Assertions" name="test5" time="0.010"/>
  <system-out>
    <![CDATA[running test5 method]]>
  </system-out>
  <testcase classname="TestNG.TestNG_Assertions" name="test3" time="0.003"/>
  <system-out>
    <![CDATA[running test3 method]]>
  </system-out>
  <testcase classname="TestNG.TestNG_Assertions" name="test6" time="0.011"/>
  <system-out>
    <![CDATA[running test6 method]]>
  </system-out>
  <testcase classname="TestNG.TestNG_Assertions" name="test1" time="0.094"/>
  <system-out>
    <![CDATA[running test1 method]]>
  </system-out>
</testsuite> <!-- TestNG.TestNG_Assertions -->
